alias cls='clear'
alias cd..='cd ..'
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias df='df -h'
alias egrep='egrep --color=auto'
alias fc='sudo fc-cache -fv'
alias fgrep='fgrep --color=auto'
alias fixpng='find . -type f -name *.png -exec convert {} -strip {} \;'
alias free='free -mt'
alias grep='grep --color=auto'
alias l='ls'
alias l.='ls -A | egrep '\''^\.'\'''
alias la='ls -a'
alias ll='ls -la'
alias ls='ls --color=auto'
alias merge='xrdb -merge ~/.Xresources'
alias mirror='sudo reflector --protocol https --latest 50 --number 20 --sort rate --save /etc/pacman.d/mirrorlist'
alias mirrors='mirror'
alias pacman='sudo pacman --color auto'
alias pdw='pwd'
alias pks='yaourt -S --noconfirm '
alias pksyu='yaourt -Syu --noconfirm'
alias pksyua='yaourt -Syu  --aur --noconfirm'
alias pmsyu='sudo pacman -Syu --color=auto'
alias ps='ps auxf'
alias psgrep='ps aux | grep -v grep | grep -i -e VSZ -e'
alias unlock='sudo rm /var/lib/pacman/db.lck'
alias update='sudo pacman -Syyu'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias userlist='cut -d: -f1 /etc/passwd'
alias vbm='sudo mount -t vboxsf -o rw,uid=1000,gid=1000 Public /home/darkrift/Public'
alias wget='wget -c'
alias size="find . -maxdepth 1 -type d -print | xargs du -sh | sort -rn"
alias kernel='echo -e "${LIGHTRED}" "Kernel Information: \t${LIGHTGRAY}" `uname -smr`'
alias usage='du -hsx * | sort -rh | head -10'
alias last-install="expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort | tail -n 20" # last 20 packages were installed
